name: Start Auto Scaling Instance Refresh

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  start-instance-refresh:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Start instance refresh
      run: |
        aws autoscaling start-instance-refresh \
          --auto-scaling-group-name my-auto-scaling-group \
          --strategy Rolling \
          --preferences '{"SkipMatching": false, "MinHealthyPercentage": 80, "InstanceWarmup": 300, "WaitTimeBetweenBatches": 600}'
